import{a as p,S as u,i}from"./assets/vendor-b0d10f48.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();async function m(e){const s="https://pixabay.com/api/",a=new URLSearchParams({key:"44028683-118753c7a8296875ea6775d6e",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15"}),o=`${s}?${a}`;return await p.get(o)}function d(e){return`
    <div class="gallery_block">
    <a href="${e.largeImageURL}">
    <img src="${e.webformatURL}" alt="${e.tags}" class="picture"></a>
    <ul class="property_list">
    <li class="property_elem">Likes <span class="span_property">${e.likes}</span></li>
    <li class="property_elem">Views <span class="span_property">${e.views}</span></li>
    <li class="property_elem">Comments <span class="span_property">${e.comments}</span></li>
    <li class="property_elem">Downloads <span class="span_property">${e.downloads}</span></li>
    </ul>
    </div>`}function y(e){return e.map(d).join("")}var f=new u(".gallery_block a",{captionsData:"alt",captionDelay:250});const g=document.querySelector(".form"),l=document.querySelector(".images_container"),c=document.querySelector(".loader");g.addEventListener("submit",async e=>{e.preventDefault(),l.innerHTML="";const s=e.target.elements.query.value.trim();if(!s)i.warning({title:"Warning",message:"You should input something",position:"topCenter"});else{c.hidden=!1;try{let a=await m(s);if(a.data.hits.length!=0){const o=y(a.data.hits);l.innerHTML=o,f.refresh()}else i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}catch{i.error({title:"Error",message:"Failed to fetch data. Please try again later!",position:"topCenter"})}finally{c.hidden=!0}}});
//# sourceMappingURL=commonHelpers.js.map
